# Generated by Django 2.2.7 on 2020-06-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64),
        ),
    ]
