# Generated by Django 2.2.7 on 2020-08-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=12)),
                ('remote_id', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=64, null=True)),
                ('source', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64, null=True)),
                ('end', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64)),
                ('transfer_status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remote_id', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64)),
                ('end', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64)),
                ('transfer_status', models.CharField(choices=[('success', 'success'), ('failed', 'failed')], max_length=12)),
                ('transferred_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.TransferredPlaylists')),
            ],
        ),
    ]
