# Generated by Django 2.2.7 on 2020-08-18 15:41

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('error', models.TextField()),
                ('source', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64)),
                ('end', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64)),
                ('type', models.CharField(choices=[('playlist', 'playlist'), ('track', 'track')], max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='transferredtracks',
            name='transferred_playlist',
        ),
        migrations.DeleteModel(
            name='TransferredPlaylists',
        ),
        migrations.DeleteModel(
            name='TransferredTracks',
        ),
    ]
