# Generated by Django 2.2.7 on 2020-07-26 19:32

from django.db import migrations, models
import musicwire.core.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(default=musicwire.core.helpers.generate_uniq_id, max_length=50)),
            ],
        ),
    ]
