# Generated by Django 2.2.7 on 2020-08-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('music', '0003_searcherrortracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=12),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searcherrortracks',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searcherrortracks',
            name='response',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CreatedPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=12)),
                ('remote_id', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('spotify', 'spotify'), ('youtube', 'youtube')], max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
