# Generated by Django 2.2.7 on 2020-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200808_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcherrortracks',
            name='response',
            field=models.TextField(max_length=255),
        ),
    ]
