# Generated by Django 2.2.7 on 2020-08-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('music', '0006_searcherrortracks_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchErrorTracks',
            new_name='SearchErrorTrack',
        ),
    ]
